const DATABASE_NAME = '@gameplay';
const COLLETION_USER = `${DATABASE_NAME}:user`;
const COLLETION_APPOINTMENTS = `${DATABASE_NAME}:appointments`;

export {
    COLLETION_USER,
    COLLETION_APPOINTMENTS
}